import type { Metadata } from 'next';
import { Providers } from './providers';
import './globals.css';

import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';
const myFont = localFont({ src: './assets/fonts/yekan.woff2' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fa" className={`${myFont.className} bg-gray-200`}>
            <body>
                <Toaster position="bottom-left" gutter={10} containerClassName="text-sm" />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
