import type { Metadata } from 'next';
import { Providers } from './providers';
import './globals.css';

import localFont from 'next/font/local';
const myFont = localFont({ src: './assets/fonts/yekan.woff2' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fa" className={`bg-gray-100 ${myFont.className}`}>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
